sudo: false
language: go

env:
    - GO111MODULE=on DOCKER_COMPOSE_VERSION=1.4.2 GRPC_PORT=8080 DB_HOST=localhost:3306 DB_USER=user-users DB_SCHEMA=userservice DB_PASSWORD=password

go:
    - 1.11.x
    - 1.12.x

before_install:
    - go get github.com/mattn/goveralls
    - sudo rm /usr/local/bin/docker-compose
    - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin
    - export top=`pwd`
    - cd ./docker/user-service/mysql
    - cd $top

script:
    - go test ./... -covermode=count -coverprofile=profile.cov
    - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci
