// Code generated by MockGen. DO NOT EDIT.
// Source: ../../service/user/service.go

// Package mock_user is a generated GoMock package.
package mock_user

import (
	gomock "github.com/golang/mock/gomock"
)
